name: Test File Upload

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
          pip show google-cloud-storage
          python -m pip install --upgrade google-cloud-storage
          pip show google-cloud-storage
          
  
      - name: Authenticate Service Account Credentials 
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{secrets.ACTIONS_SERVICE_ACCOUNT}}'

      - name: Download Model Weights
        run: python -m model_weights/download_models_from_gcs.py
      
      - name: Upload ZIP to Bucket
        run: python update_build_in_bucket.py
