name: Python Build for Windows (PyInstaller)

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: vednig/pyinstaller-action-windows@v0.1.5
        with:
          path: src
          spec: SharkEye.spec

      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: src/dist/windows
